In [1]:
import requests
import pandas as pd
import xml.etree.ElementTree as ET

In [2]:
url = "http://apis.data.go.kr/B552657/AEDInfoInqireService/getEgytAedManageInfoInqire?"

service_key = "clO+/PLnuHzh4HnDTskKmUoNxNSV3WiNk7W+fHaAEVgL7qvGErwtrfIr208DTWvrkDdJHTYgQpkD63hOf4zHxw=="

In [3]:
params = {
    "serviceKey": service_key,
    "pageNo": 1,
    "numOfRows": 10
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.text[:1000])

200
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><buildAddress>서울특별시 강남구 광평로51길 46, 수서초등학교 (수서동)</buildAddress><buildPlace>1층 보건실 앞</buildPlace><clerkTel>4591334</clerkTel><friEndTme>1630</friEndTme><friSttTme>0830</friSttTme><manager>이**</manager><managerTel>459****</managerTel><mfg>나눔테크</mfg><model>NT-381.B</model><monEndTme>1630</monEndTme><monSttTme>0830</monSttTme><org>서울수서초등학교</org><rnum>1</rnum><serialSeq>063-250423-188812</serialSeq><sunFifYon>N</sunFifYon><sunFrtYon>N</sunFrtYon><sunFurYon>N</sunFurYon><sunScdYon>N</sunScdYon><sunThiYon>N</sunThiYon><thuEndTme>1630</thuEndTme><thuSttTme>0830</thuSttTme><tueEndTme>1630</tueEndTme><tueSttTme>0830</tueSttTme><wedEndTme>1630</wedEndTme><wedSttTme>0830</wedSttTme><wgs84Lat>37.4911373654</wgs84Lat><wgs84Lon>127.1018578355</wgs84Lon><zipcode1>063</zipcode1><zipcode2>48</zipcode2></item><item><buildAddress>서울특별시 성북구 돌곶이

In [4]:
all_rows = []

page = 1
num_rows = 1000

while True:
    
    params = {
        "serviceKey": service_key,
        "pageNo": page,
        "numOfRows": num_rows
    }
    
    response = requests.get(url, params=params)
    
    if response.status_code != 200:
        print("요청 오류:", response.status_code)
        break
    
    root = ET.fromstring(response.text)
    
    result_code = root.findtext(".//resultCode")
    result_msg = root.findtext(".//resultMsg")
    
    if result_code != "00":
        print("API 오류:", result_code, result_msg)
        break
    
    items = root.findall(".//item")
    
    if len(items) == 0:
        break
    
    for item in items:
        row = {}
        
        for child in item:
            row[child.tag] = child.text
        
        all_rows.append(row)
    
    total_count = int(root.findtext(".//totalCount"))
    
    print(
        f"{page}페이지 완료 | "
        f"현재 {len(all_rows):,}건 / 전체 {total_count:,}건"
    )
    
    if len(all_rows) >= total_count:
        break
    
    page += 1

1페이지 완료 | 현재 1,000건 / 전체 63,528건
2페이지 완료 | 현재 2,000건 / 전체 63,528건
3페이지 완료 | 현재 3,000건 / 전체 63,528건
4페이지 완료 | 현재 4,000건 / 전체 63,528건
5페이지 완료 | 현재 5,000건 / 전체 63,528건
6페이지 완료 | 현재 6,000건 / 전체 63,528건
7페이지 완료 | 현재 7,000건 / 전체 63,528건
8페이지 완료 | 현재 8,000건 / 전체 63,528건
9페이지 완료 | 현재 9,000건 / 전체 63,528건
10페이지 완료 | 현재 10,000건 / 전체 63,528건
11페이지 완료 | 현재 11,000건 / 전체 63,528건
12페이지 완료 | 현재 12,000건 / 전체 63,528건
13페이지 완료 | 현재 13,000건 / 전체 63,528건
14페이지 완료 | 현재 14,000건 / 전체 63,528건
15페이지 완료 | 현재 15,000건 / 전체 63,528건
16페이지 완료 | 현재 16,000건 / 전체 63,528건
17페이지 완료 | 현재 17,000건 / 전체 63,528건
18페이지 완료 | 현재 18,000건 / 전체 63,528건
19페이지 완료 | 현재 19,000건 / 전체 63,528건
20페이지 완료 | 현재 20,000건 / 전체 63,528건
21페이지 완료 | 현재 21,000건 / 전체 63,528건
22페이지 완료 | 현재 22,000건 / 전체 63,528건
23페이지 완료 | 현재 23,000건 / 전체 63,528건
24페이지 완료 | 현재 24,000건 / 전체 63,528건
25페이지 완료 | 현재 25,000건 / 전체 63,528건
26페이지 완료 | 현재 26,000건 / 전체 63,528건
27페이지 완료 | 현재 27,000건 / 전체 63,528건
28페이지 완료 | 현재 28,000건 / 전체 63,528건
29페이지 완료 | 현재 29,000건 / 전체 63,528건
30페이지 완료 | 현재 30,000건 / 전체 63,528건
31페이지 완료 | 현재 31,000건 / 전체 63,528건
32페이지 완료 | 현재 32,000건 / 전체 63,528건
33페이지 완료 | 현재 33,000건 / 전체 63,528건
34페이지 완료 | 현재 34,000건 / 전체 63,528건
35페이지 완료 | 현재 35,000건 / 전체 63,528건
36페이지 완료 | 현재 36,000건 / 전체 63,528건
37페이지 완료 | 현재 37,000건 / 전체 63,528건
38페이지 완료 | 현재 38,000건 / 전체 63,528건
39페이지 완료 | 현재 39,000건 / 전체 63,528건
40페이지 완료 | 현재 40,000건 / 전체 63,528건
41페이지 완료 | 현재 41,000건 / 전체 63,528건
42페이지 완료 | 현재 42,000건 / 전체 63,528건
43페이지 완료 | 현재 43,000건 / 전체 63,528건
44페이지 완료 | 현재 44,000건 / 전체 63,528건
45페이지 완료 | 현재 45,000건 / 전체 63,528건
46페이지 완료 | 현재 46,000건 / 전체 63,528건
47페이지 완료 | 현재 47,000건 / 전체 63,528건
48페이지 완료 | 현재 48,000건 / 전체 63,528건
49페이지 완료 | 현재 49,000건 / 전체 63,528건
50페이지 완료 | 현재 50,000건 / 전체 63,528건
51페이지 완료 | 현재 51,000건 / 전체 63,528건
52페이지 완료 | 현재 52,000건 / 전체 63,528건
53페이지 완료 | 현재 53,000건 / 전체 63,528건
54페이지 완료 | 현재 54,000건 / 전체 63,528건
55페이지 완료 | 현재 55,000건 / 전체 63,528건
56페이지 완료 | 현재 56,000건 / 전체 63,528건
57페이지 완료 | 현재 57,000건 / 전체 63,528건
58페이지 완료 | 현재 58,000건 / 전체 63,528건
59페이지 완료 | 현재 59,000건 / 전체 63,528건
60페이지 완료 | 현재 60,000건 / 전체 63,528건
61페이지 완료 | 현재 61,000건 / 전체 63,528건
62페이지 완료 | 현재 62,000건 / 전체 63,528건
63페이지 완료 | 현재 63,000건 / 전체 63,528건
64페이지 완료 | 현재 63,528건 / 전체 63,528건

In [5]:
aed = pd.DataFrame(all_rows)

print(aed.shape)

aed.head()

(63528, 35)

,buildAddress,buildPlace,clerkTel,friEndTme,friSttTme,manager,managerTel,mfg,model,monEndTme,...,wgs84Lat,wgs84Lon,zipcode1,zipcode2,holEndTme,holSttTme,satEndTme,satSttTme,sunEndTme,sunSttTme
0,"서울특별시 강남구 광평로51길 46, 수서초등학교 (수서동)",1층 보건실 앞,4591334,1630,0830,이**,459****,나눔테크,NT-381.B,1630,...,37.4911373654,127.1018578355,063,48,NaN,NaN,NaN,NaN,NaN,NaN
1,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",1정문 경비실,02-403-0962,2400,0000,한**,010********,(주)메디아나,HeartOn A15-G4,2400,...,37.6136050803,127.0561701954,027,76,2400,0000,2400,0000,2400,0000
2,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",1관리사무실,02-403-0962,2400,0000,한**,010********,(주)메디아나,HeartOn A15-G4,2400,...,37.6136050803,127.0561701954,027,76,2400,0000,2400,0000,2400,0000
3,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",2관리사무실,02-403-0962,2400,0000,한**,010********,(주)메디아나,HeartOn A15-G4,2400,...,37.6136050803,127.0561701954,027,76,2400,0000,2400,0000,2400,0000
4,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",2정문 경비실,02-403-0962,2400,0000,한**,010********,(주)메디아나,HeartOn A15-G4,2400,...,37.6136050803,127.0561701954,027,76,2400,0000,2400,0000,2400,0000

In [6]:
aed.columns.tolist()

['buildAddress',
 'buildPlace',
 'clerkTel',
 'friEndTme',
 'friSttTme',
 'manager',
 'managerTel',
 'mfg',
 'model',
 'monEndTme',
 'monSttTme',
 'org',
 'rnum',
 'serialSeq',
 'sunFifYon',
 'sunFrtYon',
 'sunFurYon',
 'sunScdYon',
 'sunThiYon',
 'thuEndTme',
 'thuSttTme',
 'tueEndTme',
 'tueSttTme',
 'wedEndTme',
 'wedSttTme',
 'wgs84Lat',
 'wgs84Lon',
 'zipcode1',
 'zipcode2',
 'holEndTme',
 'holSttTme',
 'satEndTme',
 'satSttTme',
 'sunEndTme',
 'sunSttTme']

In [7]:
aed["wgs84Lat"] = pd.to_numeric(
    aed["wgs84Lat"],
    errors="coerce"
)

aed["wgs84Lon"] = pd.to_numeric(
    aed["wgs84Lon"],
    errors="coerce"
)

In [8]:
aed[
    ["wgs84Lat", "wgs84Lon"]
].isna().sum()

wgs84Lat    0
wgs84Lon    0
dtype: int64

In [9]:
print("전체 AED:", len(aed))

print(
    "일련번호 고유값:",
    aed["serialSeq"].nunique()
)

print(
    "중복 일련번호:",
    aed["serialSeq"].duplicated().sum()
)

전체 AED: 63528
일련번호 고유값: 63528
중복 일련번호: 0

In [10]:
aed_location_count = (
    aed
    .dropna(subset=["wgs84Lat", "wgs84Lon"])
    [["wgs84Lat", "wgs84Lon"]]
    .drop_duplicates()
    .shape[0]
)

print("AED 전체 대수:", len(aed))
print("AED 고유 위치 수:", aed_location_count)

AED 전체 대수: 63528
AED 고유 위치 수: 47251

In [11]:
aed_basic = aed[
    [
        "serialSeq",
        "org",
        "buildAddress",
        "buildPlace",
        "wgs84Lat",
        "wgs84Lon"
    ]
].copy()

aed_basic.head()

,serialSeq,org,buildAddress,buildPlace,wgs84Lat,wgs84Lon
0,063-250423-188812,서울수서초등학교,"서울특별시 강남구 광평로51길 46, 수서초등학교 (수서동)",1층 보건실 앞,37.491137,127.101858
1,027-250423-188858,장위자이레디언트아파트,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",1정문 경비실,37.613605,127.056170
2,027-250423-188859,장위자이레디언트아파트,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",1관리사무실,37.613605,127.056170
3,027-250423-188860,장위자이레디언트아파트,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",2관리사무실,37.613605,127.056170
4,027-250423-188861,장위자이레디언트아파트,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",2정문 경비실,37.613605,127.056170

In [14]:
aed.to_csv(
    "aed_raw.csv",
    index=False,
    encoding="utf-8-sig"
)
print("aed_raw.csv 저장 완료")

aed_raw.csv 저장 완료

In [15]:
aed = pd.read_csv("aed_raw.csv")

print(aed.shape)

aed.head()

(63528, 35)

,buildAddress,buildPlace,clerkTel,friEndTme,friSttTme,manager,managerTel,mfg,model,monEndTme,...,wgs84Lat,wgs84Lon,zipcode1,zipcode2,holEndTme,holSttTme,satEndTme,satSttTme,sunEndTme,sunSttTme
0,"서울특별시 강남구 광평로51길 46, 수서초등학교 (수서동)",1층 보건실 앞,4591334,1630.0,830.0,이**,459****,나눔테크,NT-381.B,1630.0,...,37.491137,127.101858,63.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN
1,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",1정문 경비실,02-403-0962,2400.0,0.0,한**,010********,(주)메디아나,HeartOn A15-G4,2400.0,...,37.613605,127.056170,27.0,76.0,2400.0,0.0,2400.0,0.0,2400.0,0.0
2,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",1관리사무실,02-403-0962,2400.0,0.0,한**,010********,(주)메디아나,HeartOn A15-G4,2400.0,...,37.613605,127.056170,27.0,76.0,2400.0,0.0,2400.0,0.0,2400.0,0.0
3,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",2관리사무실,02-403-0962,2400.0,0.0,한**,010********,(주)메디아나,HeartOn A15-G4,2400.0,...,37.613605,127.056170,27.0,76.0,2400.0,0.0,2400.0,0.0,2400.0,0.0
4,"서울특별시 성북구 돌곶이로30길 23 (장위동, 장위자이레디언트아파트)",2정문 경비실,02-403-0962,2400.0,0.0,한**,010********,(주)메디아나,HeartOn A15-G4,2400.0,...,37.613605,127.056170,27.0,76.0,2400.0,0.0,2400.0,0.0,2400.0,0.0